
package MyBookService_TopDown;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "BookExistsEx", targetNamespace = "http://MyBookService/")
public class BookExistsEx_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BookExistsEx faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BookExistsEx_Exception(String message, BookExistsEx faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BookExistsEx_Exception(String message, BookExistsEx faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: MyBookService_TopDown.BookExistsEx
     */
    public BookExistsEx getFaultInfo() {
        return faultInfo;
    }

}
