
package MyBookService_TopDown;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "MyBookService.BookService", targetNamespace = "http://MyBookService/", wsdlLocation = "file:/C:/Users/Hien/IdeaProjects/jaxws_part2/src/main/resources/bookservice.wsdl")
public class MyBookServiceBookService
    extends Service
{

    private final static URL MYBOOKSERVICEBOOKSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYBOOKSERVICEBOOKSERVICE_EXCEPTION;
    private final static QName MYBOOKSERVICEBOOKSERVICE_QNAME = new QName("http://MyBookService/", "MyBookService.BookService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Hien/IdeaProjects/jaxws_part2/src/main/resources/bookservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYBOOKSERVICEBOOKSERVICE_WSDL_LOCATION = url;
        MYBOOKSERVICEBOOKSERVICE_EXCEPTION = e;
    }

    public MyBookServiceBookService() {
        super(__getWsdlLocation(), MYBOOKSERVICEBOOKSERVICE_QNAME);
    }

    public MyBookServiceBookService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYBOOKSERVICEBOOKSERVICE_QNAME, features);
    }

    public MyBookServiceBookService(URL wsdlLocation) {
        super(wsdlLocation, MYBOOKSERVICEBOOKSERVICE_QNAME);
    }

    public MyBookServiceBookService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYBOOKSERVICEBOOKSERVICE_QNAME, features);
    }

    public MyBookServiceBookService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyBookServiceBookService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookService
     */
    @WebEndpoint(name = "BookServiceImplPort")
    public BookService getBookServiceImplPort() {
        return super.getPort(new QName("http://MyBookService/", "BookServiceImplPort"), BookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookService
     */
    @WebEndpoint(name = "BookServiceImplPort")
    public BookService getBookServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://MyBookService/", "BookServiceImplPort"), BookService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYBOOKSERVICEBOOKSERVICE_EXCEPTION!= null) {
            throw MYBOOKSERVICEBOOKSERVICE_EXCEPTION;
        }
        return MYBOOKSERVICEBOOKSERVICE_WSDL_LOCATION;
    }

}
